### ISSUE TITLE
Create user profile page 

### ISSUE THREAD

**Issue by light-200** [light-200/go-social#7]
This page should display info about the user

**Comment by shoaibahmed997** [comment]
### Hi @light-200 kindly assign the issue to me

**Comment by light-200** [comment]
Hey @shoaibahmed997 , cool you can starting working on it,
- Make sure that the profile page goes with the overall theme of the website.
- Confirm the changes you made before sending pr 
- You can post the changes you made here in the issue comments
- In case you've doubts you can join the [discord](https://discord.gg/XTDM5AwySG)

**Comment by light-200** [comment]
> try making the page within 2 days

**Comment by light-200** [comment]
@shoaibahmed997 today is the last day : )

**Comment by shoaibahmed997** [comment]
Screenshot of the Ui for User Page

<img width="1280" alt="Screenshot 2022-01-27 at 3 46 27 PM" src="https://user-images.githubusercontent.com/87946232/151339214-67b99940-c783-4ab3-a34b-5a88ca1f175f.png">
<img width="1280" alt="Screenshot 2022-01-27 at 3 46 29 PM" src="https://user-images.githubusercontent.com/87946232/151339231-a2c46368-2cad-47d3-ab5c-65e5c7ef0344.png">

**Comment by light-200** [comment]
Well done the design looks great.
